site_name: LibreConga
site_url:
repo_url: https://github.com/Xumeiquer/LibreConga
copyright: Copyright © 2021 Xumeiquer

theme:
  name: material
  favicon: images/favicon/favicon.png
  logo: images/favicon/favicon.png
  font:
    code: Roboto Mono

nav:
  - Home: index.md
  - "Research":
      - "Recon the Conga": "research/recon.md"
      - "Pairing the app": "research/pairing.md"
      - "SSL Pinning": "research/ssl-pinning.md"
      - "Protocol": "research/protocol.md"

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - toc:
      permalink: "#"

plugins:
  - search
